---
- name: Install postfix
  yum: name="postfix" state=present
  sudo: yes
  notify: restart postfix

- name: Copy configuration
  template: src=main.cf.j2 dest=/etc/postfix/main.cf owner=root group=root mode=0644
  sudo: yes
  notify: restart postfix

- service: name=postfix state=started enabled=yes
